### ISSUE TITLE
No download option

### ISSUE THREAD

**Issue by VladVidya** [Topaz-Reality/KH2Suite#1]
helo sur i cannut dl ur mod xD pls add download options??????
![2018-05-09_15-35-21](https://user-images.githubusercontent.com/20749232/39835635-b97dc4d2-539e-11e8-91df-baa8b726654b.png)

**Comment by Topaz-Reality** [comment]
fuk u i sard in grup.

**Comment by VladVidya** [comment]
i dont spek mongol sir...
